### ISSUE TITLE
TYPE not highlighted

### ISSUE THREAD

**Issue by rmcdermo** [Nevensky/SublimeFortran#2] opened 2016-02-25 15:04 UTC
Hi, I'm using your latest build of SublimeFortran-1.0.3 with latest Sublime Text 3.  First, thanks for taking on this project.  The new highlighting has solved many problems for ModernFortran.

Today I noticed that although defining a TYPE works fine, when we go to use that TYPE for a new declaration this is not highlighted.  If that was intentional, that's fine.  I was just expecting it to be highlighted, and that would be my preference.

I've attached a working file to test:

[type.f90.txt](https://github.com/315234/SublimeFortran/files/146750/type.f90.txt)

And here is a screenshot of what I'm seeing:

![type_examples](https://cloud.githubusercontent.com/assets/4418497/13323326/ea1241b2-dba6-11e5-8d67-8c78f1b68074.png)

If you can reproduce this and would like me to work on a fix, I can try, but I am not savvy with .tmLanguage.  Thanks!

**Comment by 315234** [comment] 2016-02-25 15:39
The problem was caused by the space before the "(". I've updated the .sublime-syntax file, should be fixed in v1.0.4.

**Closed as completed by 315234** 2016-02-25 15:39 UTC

**Comment by rmcdermo** [comment] 2016-02-25 15:40
Great.  Thanks!

**Comment by rmcdermo** [comment] 2016-02-25 15:45
Confirmed, works great.

On Thu, Feb 25, 2016 at 10:40 AM, Randy McDermott <randy.mcdermott@gmail.com

> wrote:
> 
> Great.  Thanks!
>
